 <div class="post">
	<p class="headingText">BMOS</p>
	<div class="flashGame">
		<center>
			<embed src="./pages/games/mbos/MetalBASEOldSkool.swf" quality="high" 
			width="640" height="480" name="BMOS" 
			loop="false"
			quality="high"
			type="application/x-shockwave-flash"
			pluginspage="http://www.adobe.com/go/getflashplayer"
			wmode="transparent"/>
		</center>
	</div>
</div>
<div class="post">
	<p class="headingText">Controls</p>
	<div class="contentText">
		Left arrow key - steer left<br/>
		Right arrow key - steer right<br/>
	</div>
	<p class="headingText">About</p>
	<div class="contentText">
		You're probably wondering WTF is this game, it makes no sense. It is called BMOS after the keywords we were given a game jam, which were 'Base-jumping', 'Metal' and 'Old-school'. The game is supposed to be a skydiving/base-jumping retro-style game, with Metal music. It's terrible, I'm sorry.
	</div>
</div> 
