<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="<?php echo $to_root;?>styles/default.css"/>
		<title>Beefy Server | <?php echo $page_title;?></title>
		<script>
var _prum = [['id', '51bbc8adabe53d0436000000'],
             ['mark', 'firstbyte', (new Date()).getTime()]];
(function() {
    var s = document.getElementsByTagName('script')[0]
      , p = document.createElement('script');
    p.async = 'async';
    p.src = '//rum-static.pingdom.net/prum.min.js';
    s.parentNode.insertBefore(p, s);
})();
		</script>
	