<?php
$pangolin_panic = array("Pangolin Panic", 
						"./images/games/pangolin_panic.png", 
						"./games/PangolinPanic/game/pangolin_panic.php",
						"Save Pangolins by firing them out of a cannon into a target. Because you care. (Requires Flash Player plugin). Made at University of Tasmania in 2010.");

$colony_defender = array("Colony Defender", 
							"./images/games/colony_defender.png", 
							"./games/ColonyDefender/colony_defender.php",
							"Navigate a hostile area of space and defeat enemies (to defend a colony). Features parallax scrolling, difficulty selection, randomly generated levels and a mini-map (Requires Flash Player). Made at University of Tasmania in 2010.");

$tanks_for_the_sheep = array("Tanks For The Sheep", 
								"./images/games/tanks_for_sheep.png", 
								"./games/TanksForTheSheep/tanks_for_the_sheep.php", 
								"Control sheeps with guns mounted to their backs. Not my game idea. The game is meant to implement node-based navigation and pathfinding using A* fastest-path searching. (Requires Unity player and Win/Mac machine). Made at University of Tasmania in 2012.");

$brain_jar_defense = array("Brain in Jar Defense",
							"./images/games/brain_jar.png",
							"./games/BrainJar/brain_jar_defense.php",
							"It is the distant future and humanity's survival is in the hands of a giant brain in a jar, that controls four robots. The robots can be instantly switched between by pressing keys 1, 2, 3, and 4. Kind of like tower defense but movable towers and first person perspective. (Requires Unity player and Win/Mac machine). Made in a Team at University of Tasmania in 2011.");

$half_life_3 = array("Half-Life 3",
					"./images/games/hl3.jpg",
					"http://half-life-3.com/is-half-life-3-out-yet",
					"Time to rise and shine, again.");
$mbos = array("MBOS",
				"./images/games/mbos_scr.png",
				"./games/MBOS/mbos.php",
				"MBOS (Metal Base Old-Skool) is a game about falling with style. Made at a friend's Game Jam in less than 24hrs in a 2 person team, I did the programming.");
							
$games = array($brain_jar_defense, $colony_defender, $pangolin_panic, $tanks_for_the_sheep, $mbos, $half_life_3);
?>

