<div class="post">
  <center>
  <p class="headingText"><span>Unity Web Player | </span>Tanks For The Sheep</p>
  <div class="content">
	  <div id="unityPlayer">
		  <div class="missing">
			  <a href="http://unity3d.com/webplayer/" title="Unity Web Player. Install now!">
				  <img alt="Unity Web Player. Install now!" src="http://webplayer.unity3d.com/installation/getunity.png" width="193" height="63" />
			  </a>
		  </div>
		  <div class="broken">
			  <a href="http://unity3d.com/webplayer/" title="Unity Web Player. Install now! Restart your browser after install.">
				  <img alt="Unity Web Player. Install now! Restart your browser after install." src="http://webplayer.unity3d.com/installation/getunityrestart.png" width="193" height="63" />
			  </a>
		  </div>
	  </div>
  </div>
  <p class="footer">&laquo; created with <a href="http://unity3d.com/unity/" title="Go to unity3d.com">Unity</a> &raquo;</p>
  </center>
  <p class="headingText">About This Game</p>
	<p class="subHeadingText">Controls</p>
	<div class="contentText">
		Click sheep to toggle selection of sheep. Right click to move sheep. <br/>
		Your sheep and enemy sheep will automatically attack each other, so move your sheep carefully!<br/>
	</div>
	<p class="subHeadingText">Loading Issues</p>
	<div class="contentText">
		The game will will likely take a while to load and probably freeze the browser. Path-finding is hard!<br/>
		Given another couple of weeks this issue would be fixed (but not a priority anymore..)<br/>
	</div>
	<p class="subHeadingText">About this game</p>
	<div class="contentText">
		This game was made at UTAS, in the unit KXG3** Advanced Games. The unit covered Artificial Intelligence in (Unity) games and also spearate to this, OpenGL graphics. 
		This game uses an A* path-finding algorithm and pre-computes the available paths to other nodes before loading, which is why it may take ages to load. 
		I used a lot of nodes, for safe measure.
	</div>
</div>