<div class="post">
	<p class="headingText">Colony Defender</p>
	<div class="flashGame">
		<center>
			<embed src="./pages/games/colony_defender/ColonyDefender.swf" quality="high" 
			width="640" height="480" name="KXG164_Game" 
			loop="false"
			quality="high"
			type="application/x-shockwave-flash"
			pluginspage="http://www.adobe.com/go/getflashplayer"
			wmode="transparent"/>
		</center>
	</div>
</div>
<div class="post">
	<p class="headingText">Controls</p>
	<div class="contentText">
		Use W,A,S,D keys to move, <br/>
		Left-click to fire lazar. <br/>
		Hold shift to lock ship to map.
	</div>
</div> 
