 <div class="post">
	<p class="headingText">Mesonoxian</p>
	<center><img src="./images/games/mesonoxian.jpg" width="700px"/></center>
	<div class="contentText">
		<a href="https://www.dropbox.com/s/yuo0n1u78v6104c/Games%20Project%20Executable.tar.gz"/>LINKZORS TO THE MAXZORS</a> (warning: ~100MB thanks to some poor image/sound compression choices)
	</div>
	<p class="headingText">About</p>
		<div class="contentText">
		This game was made for UTAS Games Project, a year-long course. I worked in a team of 8. I mostly worked on C++ programming, however we were encouraged to try other areas, and I also did some graphics (first level tiles) and lua scripting.<br/>
		In the game, you play as Vesper, an underground rebel who is hired by Secutor to steal various items from the rich and powerful oppressors of the dystopian future. Vesper must explore various levels and avoid traps. She can wall-jump and dash.
		</div>
	<p class="headingText">Controls</p>
		<div class="contentText">
		Once you download the game (see above), the controls are:<br/>
		Arrow keys: Move left/right<br/>
		Z: Jump (press whilst against a wall to wall-jump)<br/>
		X: Dash<br/>
		</div>
	</p>
</div>
