<div class="post">
	<center>
		<p class="headingText"><span>Unity Web Player | </span>Brain-In-Jar Defense</p>
		<div class="content">
			<div id="unityPlayer">
				<div class="missing">
					<a href="http://unity3d.com/webplayer/" title="Unity Web Player. Install now!">
						<img alt="Unity Web Player. Install now!" src="http://webplayer.unity3d.com/installation/getunity.png" width="193" height="63" />
					</a>
				</div>
				<div class="broken">
					<a href="http://unity3d.com/webplayer/" title="Unity Web Player. Install now! Restart your browser after install.">
						<img alt="Unity Web Player. Install now! Restart your browser after install." src="http://webplayer.unity3d.com/installation/getunityrestart.png" width="193" height="63" />
					</a>
				</div>
			</div>
		</div>
		<p class="footer">&laquo; created with <a href="http://unity3d.com/unity/" title="Go to unity3d.com">Unity</a> &raquo;</p>
	</center>
	<p class="headingText">About This Game</p>
	<p class="subHeadingText">Controls</p>
	<div class="contentText">
		1, 2, 3, 4 - to switch between robots<br/>
		W, A, S, D - to move robots<br/ >
		Mouse to look<br/>
		Escape to pause<br/>
	</div>
	<p class="subHeadingText">Story/Background</p>
	<div class="contentText">
		It is the dystopian distant future, and the zombie apocalypse has inevitably occured. <br/>
		The future humans have created the ultimate super-computer, a bio-engineered super-brain that can think creatively like a human to respond to unique situations. <br/>
		In the game, you play as the super-brain and you must control the last defenses, a base with four remote controlled robots. <br/>
		As zombies enjoy the taste of brains, they are drawn towards the super brain. This mean more zombie killing! <br/>
		The gameplay is a hybrid of tower-defense and FPS. You can switch bewtween each robot (or TD tower) effectively moving towers around and taking control of them from the first perosn perpective. <br/>
		<br/>
		Due to limited base power, the robots have a very limited range, and cannot be moved far outside the base. Static interference indicates loss of reception.<br/>
	</div>
</div>