<div class="post">
    <p class="headingText">Misc Stuff</p>
    <div class="contentText">
    <p class="subHeadingText"><a href="?page=r_pi">My Raspberry Pi (Redirect)</a></p>
	<p class="subHeadingText"><a href="?page=steam_games">Steam Games Picker</a></p>
	<p class="subHeadingText"><a href="?page=tts_server">Text to speech</a></p>
	<p>Various small things put here for the purposes of learning and mucking about, which is important to do. </p>
	
    </div>
</div>
