<div class="post">
	<p class="headingText">Pangolin Panic</p>
	<div class="flashGame">
		<center>
			<embed src="./pages/games/pangolin_panic/game/KXG164_Game.swf"
			quality="high"
			width="768" height="640" name="KXG164_Game" 
			loop="false"
			type="application/x-shockwave-flash"
			pluginspage="http://www.adobe.com/go/getflashplayer"
			wmode="transparent"
			AllowScriptAccess="always"/>
		</center>
	</div>
</div>
<div class="post">
	<p class="headingText">Issues</p>
	<div class="contentText">
		Game may not be working in browser for unknown reasons (Adobe's fault).<br/>
		Try loading <a href="./pages/games/pangolin_panic/game/KXG164_Game.swf">the SWF directly here</a>,<br/>
		or downloading the <a href="./pages/games/pangolin_panic/game.zip">whole game standalone.</a>
	</div>
	<p class="headingText">Controls</p>
	<div class="contentText">
		Left click to shoot. More info in-game.
	</div>
</div> 

